name: CI/CD for Frontend

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Set this secret in GitHub

    - name: Deploy to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name shezanadev  \
          --destination '$web' \
          --source '.'  # Use current directory as source
